use_frameworks!

platform :ios, '9.0'

target 'BZMWebViewJSBridge_Example' do
  pod 'BZMWebViewJSBridge', :path => '../'

  target 'BZMWebViewJSBridge_Tests' do
    inherit! :search_paths

    
  end
end
